attractions_list = ['47th Street - The Diamond District', '9/11 Memorial & Museum',
                    'Abyssinian Baptist Church', 'Alice Austen House Museum',
                    'Alice Tully Hall', 'Alvin Ailey American Dance Theate',
                    'American Girl Place', 'American Museum of Natural History',
                    'Apollo Theater', 'arts>Brookfield Place', 'Barclays Center',
                    'Bartow-Pell Mansion Museum', 'Bateaux New York',
                    'Bronx Brewery', 'Bronx Library Center', 'Bronx Zoo',
                    'Brooklyn Botanic Garden', 'Brooklyn Bridge',
                    'Brooklyn Heights Promenade', 'Brooklyn Historical Society',
                    'Brooklyn Navy Yard', 'Brooklyn Nets', 'Brooklyn Public Library',
                    'Calvary Cemetery', 'Carnegie Hall',
                    'Cathedral Church of St. John the Divine',
                    'Central Park Conservancy—Official Central Park Tours',
                    'Charles A. Dana Discovery Center/Harlem Meer',
                    'Chelsea Craft Brewing Company',
                    'Chelsea Piers Sports & Entertainment Complex',
                    'Chrysler Building', 'Circle Line Downtown',
                    'Circle Line Sightseeing Cruises', 'City Hall',
                    'City Hall Park', 'Classic Harbor Line LLC',
                    'Clove Lakes Park', 'Coney Island Brewing Company',
                    'Coney Island Circus Sideshow', 'Delacorte Theate',
                    'Douglaston Golf Course', 'Duffy Square',
                    'Ellis Island', 'Ellis Island National Museum of Immigration',
                    'Ellis Island/American Family Immigration History Center',
                    'Empire State Building Experience', 'FDNY Fire Zone',
                    'Flatiron Building', 'Flushing Meadows Corona Park',
                    'Fort Tryon Park', 'Governors Island', 'Gramercy Park',
                    'Grand Army Plaza', 'Grand Army Plaza Memorial Arch',
                    'Grand Central Terminal', 'Green-Wood Cemetery',
                    'Greenbelt Nature Center', "Gulliver's Gate", 'Hell Gate Bridge',
                    "Hershey's Chocolate World Times Square", 'Historic Richmond Town',
                    'Holographic Studios', 'Hunters Point Community Library',
                    'Intrepid Sea, Air & Space Museum', 'Irish Hunger Memorial',
                    'Jacqueline Kennedy Onassis Reservoir', 'James A. Farley Post Office',
                    "Jane's Carousel", 'Jazz at Lincoln Center', "Jeffrey's Hook Lighthouse",
                    'Loeb Central Park Boathouse', 'Luna Park at Coney Island',
                    "Macy's Herald Square", 'Madison Square Garden', 'Mahayana Buddhist Temple',
                    'McCarren Park', 'Museum at Eldridge Street Synagogue', 'Museum Mile',
                    'Museum of American Finance', 'Mystery Room NYC', 'National Geographic Encounter: Ocean Odyssey',
                    'National Parks of New York Harbor', 'New York Botanical Garden', 'New York City FC',
                    'New York Hall of Science', 'New York Knicks', 'New York Public Library, Stephen A. Schwarzman Building',
                    'New York Rangers', 'New York Transit Museum', 'New York Wheel', 'New York Yankees',
                    "Official NYC Information Center at Macy's Herald Square", 'Old Stone House',
                    'One World Observatory', 'Parachute Jump', 'Paradise Theater', 'Pepsi-Cola Sign',
                    'Plymouth Church of the Pilgrims', 'Poe Park', 'Prospect Park',
                    'Prospect Park Audubon Center', 'Prospect Park Carousel', 'Prospect Park Lake',
                    'Prospect Park Litchfield Villa', 'Prospect Park Zoo', 'Queens Museum', 'Queens Zoo',
                    'Queensboro Bridge', 'Radio City Music Hall', 'Resorts World Casino New York City',
                    "Ripley's Believe It or Not! Times Square", 'Riverside Park', 'Rockefeller Center',
                    'Roosevelt Island', 'Roundabout Theatre Company', 'Sail the Park',
                    'Schomburg Center for Research in Black Culture', 'SeaGlass Carousel',
                    'Seaport District NYC', 'Sheep Meadow, Central Park', 'Sleep No More',
                    'Socrates Sculpture Park', 'Solomon R. Guggenheim Museum', 'South Street Seaport Museum',
                    'Spirit of New York', "St. Patrick's Cathedral", 'St. Patrick’s Old Cathedra',
                    "St. Paul's Chapel", 'Staten Island Borough Hall', 'Staten Island Ferry',
                    'Staten Island September 11 Memorial', 'Staten Island Yankees', 'Staten Island Zoo',
                    'Statue of Liberty National Monument', 'Strawberry Fields/Imagine Mosaic',
                    'The Church of St. Luke in the Fields', 'The Cyclone', 'The Frick Collection',
                    'The High Line', 'The Met Breuer', 'The Met Cloisters', 'The Met Fifth Avenue',
                    'The Metropolitan Opera', 'The Museum of Modern Art (MoMA)',
                    "The New York Chinese Scholar's Garden", 'The New York Pass',
                    'The New-York Historical Society', 'The PIT', 'The Plaza Hotel',
                    'The Ride', 'The Rink at Rockefeller Center', 'The Riverside Church New York City',
                    'The Tenement Museum', 'The Thunderbolt', 'The Tour at NBC Studios', 'The Town Hall',
                    'Theodore Roosevelt Birthplace', 'Times Square', 'Top of the Rock Observation Deck',
                    'Turtle Pond', 'Underpenny Plane and Cast Iron Museum', 'United Nations',
                    'United Palace House of Inspiration', 'USTA Billie Jean King National Tennis Center',
                    'Van Cortlandt House Museum', 'Verrazano-Narrows Bridge',
                    'Victorian Gardens Amusement Park (Central Park)', 'VR World NYC', 'Wall Street',
                    'Washington Square Park', 'Waterfront at Brookfield Place', 'Wave Hill',
                    'Wildlife Conservation Society', 'Williamsburg Bridge', 'Woodlawn Cemetery',
                    'World Trade Center Transportation Hub', 'Wyckoff Farmhouse Museum',
                    'African Burial Ground National Monument', 'Manhattan Bridge', 'Conservatory Garden',
                    'Mount Vernon Hotel Museum & Garden', 'St. George Theatre', 'Explorer Pass',
                    'Wollman Rink', 'Friedsam Memorial Carousel', 'Japan Society', 'FDNY Fire Zone Rockefeller Center',
                    'TimeLooper`', 'On Location Tours, Inc.', 'Snug Harbor Cultural Center & Botanical Garden', 'Voilà Chocolat',
                    'Central Park Zoo', 'Asser Levy/Seaside Park', 'Woolworth Building', 'Brookfield Place',
                    'New York Mets', 'Onassis Cultural Center New York', 'Official NYC Information Center–South Street Seaport',
                    'Fort Wadsworth', "Deno's Wonder Wheel Amusement Park", 'Bethesda Terrace/Fountain',
                    'The Public Theate', 'Washington Street between Front and Water Streets', 'Brooklyn Bridge Park',
                    'Tompkins Square Park', 'Lincoln Center for the Performing Arts', 'National Park Service',
                    'Belvedere Castle', 'Sunset Park', 'Official NYC Information Center (Times Square)', 'Morris-Jumel Mansion',
                    'Conservatory Water', 'Madame Tussauds New York', 'Whitney Museum of American Art', 'Coney Island History Project',
                    'United Palace Theatre', 'Central Park', 'Bank of America Winter Village at Bryant Park', 'New York City Ballet',
                    'Museum of Sex', 'Coney Island', 'Unbreakable Kimmy Schmidt Apartment', 'Bryant Park', 'Citi Field',
                    'Queens Botanical Garden', 'Prospect Park Bandshell', 'Prospect Park Concert Grove', 'The Mall and Literary Walk',
                    'IFC Center', 'Andrew Heiskell Braille and Talking Book Library', 'Brooklyn Borough Hall', 'New York Aquarium',
                    'Yankee Stadium', 'High Bridge', 'One World Trade Center', '9/11 Memorial Museum Store', 'Madison Square Park',
                    'New York Philharmonic', 'Gracie Mansion', 'Trinity Wall Street', 'Brooklyn Cyclones', 'Bronx Zoo Treetop Adventure',
                    'West 4th Street Courts', 'Staten Island Yankees', 'Manhattan by Sail', 'Manhattan by Sail', 'New York Stock Exchange',
                    'Hook & Ladder Company 8', 'Grand Masonic Lodge of New York', 'St. Mark’s Place', 'Franklin D. Roosevelt Four Freedoms Park',
                    'Gray Line CitySightseeing New York Bus Tours', 'Abracadabra Superstore', 'Brooklyn Brewery', 'Kingsland Homestead',
                    'French Institute Alliance Française', 'Commodore Barry Park', "Saint Augustine's Episcopal Church", 'Casa Belvedere',
                    "Merchant's House Museum", 'Kissena Park', 'Alley Pond Park', 'The Battery', 'Emmanuel Baptist Church',
                    'UNICEF House—Danny Kaye Visitors Centre', 'St. Ann & The Holy Trinity Church', 'Hoodwinked Escape',
                    'Flatbush Dutch Reformed Church', 'Staten Island Supreme Courthouse', 'Adam Yauch Park', 'Islamic Cultural Center of New York',
                    'Roosevelt House Public Policy Institute at Hunter College', 'Old Quaker Meeting House', 'Go Select NYC',
                    'Weeksville Heritage Center', 'The Sightseeing Pass', 'Hudson Yards New York', '34th Street Partnership',
                    'General Grant National Memorial', 'Pier 25, Hudson River Park', '55 Central Park West', 'Sara D. Roosevelt Park',
                    'Central Park Arsenal', 'InterChurch Center', 'Sakura Park', 'Pelham Bay Park', 'Hudson River Park', 'LIC Flea & Food',
                    "Grant's Tomb", 'Gravesend Cemetery', 'Piers 92/94 New York', 'New York Marble Cemetery', 'New York City AIDS Memorial',
                    'Peter Jay Sharp Theater at Julliard', 'Chester A. Arthur House', 'Chateau Stables', 'LIC Beer Project',
                    "Central Park's Rumsey Playfield", 'Christie’s Auction House', 'Lasker Rink', 'Marble Collegiate Church',
                    'Riverdale Park', 'Brooklyn Army Terminal', 'NYC Department of Records and Information Services', 'City Ice Pavilion',
                    'Floyd Bennett Field', '69th Regiment Armory', 'Federal Hall National Memorial', 'Scandinavia House: The Nordic Center in America',
                    'NYRR RunCenter Featuring the New Balance Run Hub', 'Bowling Green Park', 'New York City Horse Carriages',
                    'New York Public Library for the Performing Arts', 'Empire Stores', 'Central Park Bandshell', 'The Players Theatre',
                    'Lefferts Historic House', 'Ford Amphitheater at Coney Island Boardwalk', 'MetLife Building', 'Valentine-Varian House',
                    'Bronx Council on the Arts', 'NFL Experience Times Square', "Randall's Island Park", 'Ed Sullivan Theater', 'Essex Street Market',
                    'The Conference House Museum', 'Pier 45', 'Riverbank State Park Ice Rink', 'American Stock Exchange Building', 'Pier 40',
                    'Long Island City Partnership', 'The Great Hall, Cooper Union', 'Czech Center New York',
                    'The Malcolm X and Dr. Betty Shabazz Memorial & Educational Center', '79th Street Boat Basin',
                    'New York City Center', 'Electric Lady Studios', 'Harlem Park to Park', "St. Bartholomew's Church",
                    'Kissena Golf Course', 'Riverside Park South', 'Poets House']